name: Build PDF resume and upload it

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tex"
      - "**/*.cls"
      - ".github/workflows/*.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest # Debian-based
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y fonts-noto

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile
        run: |
          for texfile in *.tex; do
            make pdf "$texfile"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: build/*.pdf

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: resumes

      - name: Upload resumes to bucket
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.R2_API_TOKEN_RESUME_GITHUB }}
          command: |
            for pdf in *.pdf; do
              r2 object put ${{ secrets.BUCKET_NAME }}/personal/$(basename $pdf) --file=$pdf
            done
