name: Build PDF resume and upload it

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest # Debian-based
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y fonts-noto

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile
        run: |
          for texfile in *.tex; do
            make pdf "$texfile"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: build/*.pdf

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: resumes

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Upload PDFs to bucket
        run: |
          PREFIX="personal"
          for pdf in *.pdf; do
            aws s3api put-object --endpoint-url ${{ secrets.S3_API_ENDPOINT }} --bucket ${{ secrets.BUCKET_NAME }} --key $PREFIX/$pdf --body $pdf
          done
